In [2]:
import colorcet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
import plotly.colors as colors

In [3]:
df=pd.read_csv("D:/data science/data analysis/E-Commerce/Sample - Superstore.csv",encoding="latin1")

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

convert order date and ship date format from object to datetime

In [6]:
df['Order Date']=pd.to_datetime(df['Order Date'])
df['Ship Date']=pd.to_datetime(df['Ship Date'])
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

**Now we are going to add 3 new coloum for better analysis (order month ow.oy)**

In [34]:
df['order_month']=df['Order Date'].dt.month
df['order_year']=df['Order Date'].dt.year
df['order day of week']=df['Order Date'].dt.dayofweek
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,order_month,order_year,order day of week
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,11,2016,1
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,11,2016,1
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,6,2016,6
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,10,2015,6
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,10,2015,6

**QUESTION** ::   *YOU NEED TO CALCULATE THE MONTHLY SALE OF THE STORE AND IDENTIFY WHICH MONTH HAD THE HIGHEST SALE AND WHICH MONTH HAD LOWEST SALE*

In [35]:
sales_by_month=df.groupby('order_month')['Sales'].sum().reset_index()
sales_by_month

    order_month        Sales
0             1   94924.8356
1             2   59751.2514
2             3  205005.4888
3             4  137762.1286
4             5  155028.8117
5             6  152718.6793
6             7  147238.0970
7             8  159044.0630
8             9  307649.9457
9            10  200322.9847
10           11  352461.0710
11           12  325293.5035

In [36]:
#plt.plot(sales_by_month)
#plt.show()
px.line(sales_by_month,x='order_month',y='Sales',title='Sales by Month',markers='0')

**Question2**
You need to analyze sales based on product categories and determine which category has
the lowest sales and which category has the highest sales.

In [37]:
sales_by_category=df.groupby('Category')['Sales'].sum().reset_index()
sales_by_category

          Category        Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [38]:
fig=px.pie(sales_by_category,values='Sales',names='Category',title='Categories',hole=0.5, color_discrete_sequence=px.colors.qualitative.Pastel1)
fig.update_traces(textposition='inside',textinfo='percent+label')
fig.update_layout(title_text='Sales by Category')

fig.show()

**QUESTION3**The sales analysis needs to be done based on sub-categories

In [39]:
sales_by_subcategory=df.groupby(['Sub-Category'])['Sales'].sum().reset_index()
sales_by_subcategory

   Sub-Category        Sales
0   Accessories  167380.3180
1    Appliances  107532.1610
2           Art   27118.7920
3       Binders  203412.7330
4     Bookcases  114879.9963
5        Chairs  328449.1030
6       Copiers  149528.0300
7     Envelopes   16476.4020
8     Fasteners    3024.2800
9   Furnishings   91705.1640
10       Labels   12486.3120
11     Machines  189238.6310
12        Paper   78479.2060
13       Phones  330007.0540
14      Storage  223843.6080
15     Supplies   46673.5380
16       Tables  206965.5320

In [1]:
fig1=px.bar(sales_by_subcategory,x='Sub-Category',y='Sales',title='Sales by Sub-Category',color='Sub-Category')
fig1.update_traces(textposition='inside')

NameError: name 'px' is not defined

In [41]:
fig1.show()

**QUESTION:4** You need to analyze the monthly profit from sales and determine which month had the
highest profit.

In [42]:
profit_by_month=df.groupby('order_month')['Profit'].sum().reset_index()
profit_by_month

    order_month      Profit
0             1   9134.4461
1             2  10294.6107
2             3  28594.6872
3             4  11587.4363
4             5  22411.3078
5             6  21285.7954
6             7  13832.6648
7             8  21776.9384
8             9  36857.4753
9            10  31784.0413
10           11  35468.4265
11           12  43369.1919

In [43]:
fig2=px.line(profit_by_month,x='order_month',y='Profit',title='Profit by Month',markers='0')
fig2.show()

**QUESTION : 5** Analyze the profit by category and sub-category.

In [44]:
profit_by_category=df.groupby(['Category'])['Profit'].sum().reset_index()
profit_by_category

          Category       Profit
0        Furniture   18451.2728
1  Office Supplies  122490.8008
2       Technology  145454.9481

In [45]:
fig3=px.pie(profit_by_category,values='Profit',names='Category',hole=0.3)
fig3

**profit by subcategory**

In [46]:
profit_by_subcategory=df.groupby(['Sub-Category'])['Profit'].sum().reset_index()

In [47]:
fig4=px.bar(profit_by_subcategory,x='Sub-Category',y='Profit',title='Profit by Sub-Category',color='Sub-Category')
fig4.show()

**QUESTION : 5** Analyze the sales and profit by customer segmen

In [48]:
profit_By_segment = df.groupby(['Segment']).agg({'Sales': 'sum', 'Profit': 'sum'}).reset_index()

color_palette = px.colors.qualitative.Pastel
fig5 = go.Figure()
fig5.add_trace(go.Bar(
    x=profit_By_segment['Segment'],
    y=profit_By_segment['Sales'],
    marker_color=color_palette[0]
))
fig5.add_trace(go.Bar(x=profit_By_segment['Segment'], y=profit_By_segment['Profit'], marker_color=color_palette[1]))
fig5.show()

**QUESTION:6** Analyze the sales to profit ratio

In [59]:
sales_profit_by_segment = df.groupby(['Segment']).agg({'Sales': 'sum', 'Profit': 'sum'}).reset_index()
sales_profit_by_segment['sales_to_ratio']=sales_profit_by_segment['Sales'] / sales_profit_by_segment['Profit']
print(sales_profit_by_segment[['Segment','sales_to_ratio']])

       Segment  sales_to_ratio
0     Consumer        8.659471
1    Corporate        7.677245
2  Home Office        7.125416